// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvhgjiksyyfhnswcvsqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2aGdqaWtzeXlmaG5zd2N2c3FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDk3MzQsImV4cCI6MjA2MjM4NTczNH0.JvuFQda5fOOaSAPloT2XPQ4-k715vBX8-OX0Sjz9si0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});