// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udzrkapsvgqgsbjpgkxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkenJrYXBzdmdxZ3NianBna3hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzEzODIsImV4cCI6MjA3MzEwNzM4Mn0.7oxZI11jFH-S7c2RMCb5Y0i2BrFcLclApJGEWl76IIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});